### ISSUE TITLE
IR-National code error when input is integer

### ISSUE THREAD

**Issue by ma2783930** [sadegh19b/laravel-persian-validation#14]
Hi
With LaravelExcel package when you try to use ir_national_code validator, the input value for **validateIranianNationalCode** method in _PersianValidators.php_ is integer, so **line 378** throws with an exception of: _Trying to access array offset on value of type int_.

Please add **string cast** for $value input in method to avoid this error.

Thank you for helpful package.

**Comment by sadegh19b** [comment]
Hi, Sorry for my late reply. Thanks to @mojtabaRKS, I think your problem has been solved with this [pull request](https://github.com/sadegh19b/laravel-persian-validation/pull/15), test it and let me know the result, thank you.
