### ISSUE TITLE
code can refactored 

### ISSUE THREAD

**Issue by mojtabaRKS** [sadegh19b/laravel-persian-validation#16]
you can use the `str_pad` instead of if else statement :
https://github.com/sadegh19b/laravel-persian-validation/blob/9121469e5c472e90c01795d53453defa55c006f3/src/PersianValidators.php#L371C9-L375C10

and you can use single statement instead of this :
https://github.com/sadegh19b/laravel-persian-validation/blob/9121469e5c472e90c01795d53453defa55c006f3/src/PersianValidators.php#L387C9-L391C10

i refactored these issues in this PR:
https://github.com/sadegh19b/laravel-persian-validation/pull/15

**Comment by sadegh19b** [comment]
Thank you
